In [15]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

In [16]:
documents = [
    "Machine learning is a subset of artificial intelligence that allows systems to learn from data.",
    "Deep learning uses neural networks with many layers to model complex patterns in data.",
    "Gradient descent is an optimization algorithm used to minimize the loss function in machine learning.",
    "Neural networks are inspired by the structure of the human brain and consist of layers of neurons.",
    "Natural language processing enables computers to understand and generate human language.",
    "Support vector machines are supervised learning models used for classification and regression tasks.",
    "Backpropagation is the algorithm used to train neural networks by computing gradients.",
    "Overfitting occurs when a model learns the training data too well and fails to generalize.",
    "Python is the most popular programming language for machine learning and data science.",
    "Convolutional neural networks are widely used in image recognition and computer vision tasks."
    ]

In [17]:
vec = TfidfVectorizer(stop_words = 'english')
vec

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,analyzer,'word'
,stop_words,'english'
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"


In [18]:
X = vec.fit_transform(documents)   
print(X.shape)

(10, 66)


In [19]:
svd = TruncatedSVD(n_components = 4, random_state = 42)
X_lsa = svd.fit_transform(X)
print(X_lsa)

[[ 0.3625719   0.49460761  0.15289789 -0.25234644]
 [ 0.59260519 -0.04878689 -0.4090831  -0.27092377]
 [ 0.41528243  0.11163298  0.53327841 -0.01197117]
 [ 0.41822612 -0.31782732 -0.48428583  0.23539193]
 [ 0.18550693  0.31466198 -0.23339223  0.73509273]
 [ 0.31143447 -0.0989639   0.45939057 -0.00785627]
 [ 0.48776826 -0.42300161  0.16062407  0.06339118]
 [ 0.23392908  0.220378   -0.36198662 -0.54312752]
 [ 0.42225458  0.62025603  0.03267042  0.21473883]
 [ 0.43896671 -0.45228534  0.13857676  0.06859177]]


In [20]:
#q = input("Query: ")
q = ["Explain what is Neural Networks"]
q_TfIdf = vec.transform(q)


In [21]:
q_LA = svd.transform(q_TfIdf)
q_LA

array([[ 0.42022348, -0.33994896, -0.17703591,  0.0305716 ]])

In [22]:
similarities = cosine_similarity(q_LA, X_lsa)[0]
similarities

array([-0.13044054,  0.75096594,  0.10707326,  0.87923939,  0.07154689,
        0.25828481,  0.84658614,  0.17100929, -0.07334364,  0.8542845 ])

In [23]:
ranking = similarities.argsort()[::-1]
ranking


array([3, 9, 6, 1, 5, 7, 2, 4, 8, 0])

In [24]:
for rank, i in enumerate(ranking):
    print(f"Rank {rank+1} (score={similarities[i]:.4f}): {documents[i]}")

Rank 1 (score=0.8792): Neural networks are inspired by the structure of the human brain and consist of layers of neurons.
Rank 2 (score=0.8543): Convolutional neural networks are widely used in image recognition and computer vision tasks.
Rank 3 (score=0.8466): Backpropagation is the algorithm used to train neural networks by computing gradients.
Rank 4 (score=0.7510): Deep learning uses neural networks with many layers to model complex patterns in data.
Rank 5 (score=0.2583): Support vector machines are supervised learning models used for classification and regression tasks.
Rank 6 (score=0.1710): Overfitting occurs when a model learns the training data too well and fails to generalize.
Rank 7 (score=0.1071): Gradient descent is an optimization algorithm used to minimize the loss function in machine learning.
Rank 8 (score=0.0715): Natural language processing enables computers to understand and generate human language.
Rank 9 (score=-0.0733): Python is the most popular programming lan