In [1]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.decomposition import TruncatedSVD
from sklearn.metrics.pairwise import cosine_similarity

In [2]:
documents = [
    "A car, or an automobile, is a motor vehicle with wheels. Most definitions of cars state that they run primarily on roads, seat 1-8 people, have four wheels, and mainly transport people rather than cargo. There are over 1.6 billion cars in use worldwide as of 2025.",
    "The development of external combustion (also known as steam) engines is detailed in the history of the car. Still, it is often treated separately from the development of cars in their modern understanding. A variety of steam-powered road vehicles were used during the first part of the 19th century, including steam cars, steam buses, phaetons, and steam rollers. In the United Kingdom, sentiment against them led to the Locomotive Acts of 1865.",
    "The dog (Canis familiaris or Canis lupus familiaris) is a domesticated descendant of wolves. Also called the domestic dog, it was selectively bred during the Late Pleistocene by hunter-gatherers. Dogs and the modern gray wolf share a common ancestor.[4] Dogs were the first species to be domesticated over 14,000 years ago, before the development of agriculture, though genetic studies suggest the domestication process may have begun over 25,000 years ago. Due to their long association with humans, dogs have gained the ability to thrive on a starch-rich diet that would be inadequate for other canids.",
    "canine animal care and nutrition",
    "A pet, or companion animal, is an animal kept primarily for a person's company or entertainment rather than as a working animal, livestock, or a laboratory animal. Popular pets are often considered to have attractive/cute appearances, intelligence, and relatable personalities, but some pets may be taken in on an altruistic basis (such as a stray animal) and accepted by the owner regardless of these characteristics. Two of the most popular pets are dogs and cats. Other animals commonly kept include rabbits; ferrets; pigs; rodents such as gerbils, hamsters, chinchillas, rats, mice, and guinea pigs; birds such as parrots, passerines, and fowls; reptiles such as turtles, lizards, snakes, and iguanas; aquatic pets such as fish, freshwater snails, and saltwater snails; amphibians such as frogs and salamanders; and arthropod pets such as tarantulas and hermit crabs. Smaller pets include rodents, while the equine and bovine group include the largest companion animals."
]

In [3]:
vec = TfidfVectorizer(stop_words = 'english')
vec

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,analyzer,'word'
,stop_words,'english'
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"


In [4]:
X = vec.fit_transform(documents)   
print(X.shape)

(5, 165)


In [5]:
svd = TruncatedSVD(n_components = 4, random_state = 42)
X_lsa = svd.fit_transform(X)
print(X_lsa)

[[ 1.02899905e-01  6.85216166e-01 -3.42257160e-01 -6.28332746e-01]
 [ 8.40694994e-02  7.32463421e-01  7.83515188e-16  6.71657757e-01]
 [ 1.17537820e-01  2.36687829e-01  9.34177237e-01 -2.17039120e-01]
 [ 7.39463041e-01 -1.32972772e-01 -1.00860926e-01  1.21933998e-01]
 [ 7.51093494e-01 -8.19842452e-02 -2.91736602e-15 -7.51782992e-02]]


In [7]:
#q = input("Query: ")
q = ["automobile engine"]
q_TfIdf = vec.transform(q)


In [11]:
q_LA = svd.transform(q_TfIdf)
q_LA

array([[ 0.01736478,  0.12159006, -0.065983  , -0.1325977 ]])

In [14]:
similarities = cosine_similarity(q_LA, X_lsa)[0]
similarities

array([ 0.99664588,  0.00760739, -0.01066309, -0.08691726,  0.08927517])

In [16]:
ranking = similarities.argsort()[::-1]
ranking


array([0, 4, 1, 2, 3])